version: '3.7'

services:

  sgqclient:
    image:
      sgq/sgqclient:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "2828:80"