version: '3.7'

services:

  sgqclient:
    container_name: sgqclient
    image:
      arnaldobichara/sgqclient:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - APIGwUrl=http://${SGQ_SERVER_DNS_NAME_OR_IP}:5202

    ports:
      - "80:80"